import { gsap } from "gsap"

export function tentacleSway() {
    var swayTL = gsap.timeline();
    swayTL.to("#RT-P1", { duration: 1, rotation: -20, ease: "none" }, "sway-out")
        .to("#RT-Joint-1", { duration: 1, rotation: -20, translateX: 15, translateY: -5, ease: "none" }, "sway-out")
        .to("#RT-Panel-2", { duration: 1, rotation: -30, translateX: 20, translateY: -5, ease: "none" }, "sway-out")
        .to("#RT-Joint-2", { duration: 1, rotation: -30, translateX: 60, translateY: -15, ease: "none" }, "sway-out")
        .to("#RT-Panel-3", { duration: 1, rotation: -20, translateX: 65, translateY: -17, ease: "none" }, "sway-out")
        .to("#RT-Joint-3", { duration: 1, rotation: -15, translateX: 88, translateY: -24, ease: "none" }, "sway-out")
        .to("#RT-P4", { duration: 1, translateX: 100, translateY: 210, ease: "none" }, "sway-out")
        .to("#RT-Joint-4", { duration: 1, rotation: 5, translateX: 92, translateY: -27, ease: "none" }, "sway-out")
        .to("#RT-P5", { duration: 1, rotation: 15, translateX: 116, translateY: 276, ease: "none" }, "sway-out")
        .to("#RT-Joint-5", { duration: 1, rotation: 20, translateX: 88, translateY: -23, ease: "none" }, "sway-out")
        .to("#RT-Spear", { duration: 1, rotation: 25, translateX: 120, translateY: 300, ease: "none" }, "sway-out")

        .to("#LT-P1", { duration: 1, rotation: -20, ease: "none" }, "sway-out")
        .to("#LT-Joint-1", { duration: 1, rotation: -20, translateX: 15, translateY: -5, ease: "none" }, "sway-out")
        .to("#LT-Panel-2", { duration: 1, rotation: -30, translateX: 20, translateY: -5, ease: "none" }, "sway-out")
        .to("#LT-Joint-2", { duration: 1, rotation: -30, translateX: 60, translateY: -15, ease: "none" }, "sway-out")
        .to("#LT-Panel-3", { duration: 1, rotation: -20, translateX: 65, translateY: -17, ease: "none" }, "sway-out")
        .to("#LT-Joint-3", { duration: 1, rotation: -15, translateX: 88, translateY: -24, ease: "none" }, "sway-out")
        .to("#LT-P4", { duration: 1, translateX: 100, translateY: 210, ease: "none" }, "sway-out")
        .to("#LT-Joint-4", { duration: 1, rotation: 5, translateX: 92, translateY: -27, ease: "none" }, "sway-out")
        .to("#LT-P5", { duration: 1, rotation: 15, translateX: 116, translateY: 276, ease: "none" }, "sway-out")
        .to("#LT-Joint-5", { duration: 1, rotation: 20, translateX: 88, translateY: -23, ease: "none" }, "sway-out")
        .to("#LT-Spear", { duration: 1, rotation: 25, translateX: 120, translateY: 300, ease: "none" }, "sway-out")

        .to("#RT-P1", { duration: 1, rotation: 0, ease: "none" }, "sway-in")
        .to("#RT-Joint-1", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-Panel-2", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-Joint-2", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-Panel-3", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-Joint-3", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-P4", { duration: 1, translateX: 10, translateY: 238, ease: "none" }, "sway-in")
        .to("#RT-Joint-4", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-P5", { duration: 1, rotation: 0, translateX: 25, translateY: 303, ease: "none" }, "sway-in")
        .to("#RT-Joint-5", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#RT-Spear", { duration: 1, rotation: 0, translateX: 35, translateY: 325, ease: "none" }, "sway-in")

        .to("#LT-P1", { duration: 1, rotation: 0, ease: "none" }, "sway-in")
        .to("#LT-Joint-1", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-Panel-2", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-Joint-2", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-Panel-3", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-Joint-3", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-P4", { duration: 1, translateX: 10, translateY: 238, ease: "none" }, "sway-in")
        .to("#LT-Joint-4", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-P5", { duration: 1, rotation: 0, translateX: 25, translateY: 303, ease: "none" }, "sway-in")
        .to("#LT-Joint-5", { duration: 1, rotation: 0, translateX: 0, translateY: 0, ease: "none" }, "sway-in")
        .to("#LT-Spear", { duration: 1, rotation: 0, translateX: 35, translateY: 325, ease: "none" }, "sway-in")

    return swayTL.repeat(30)
}